### ISSUE TITLE
OTSi Information in the Flexi-grid tunnel model

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang#40]
> Moreover the knowledge of the OTSi position in the spectrum is also useful in the intermediate nodes to easy the Optical Channel Monitoring in the ROADM."

I think this piece of text is very important when discussing the information to be provided by the controller (or by the control plane) to a ROADM during path setup. However, I am not sure this has an impact to the information to be provided in the topology model for path computation. My proposal is not to put this sentence in this draft but to open an issue to discuss this sentence in the context of tunnel setup: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/89#issuecomment-923907647

**Comment by danielkinguk** [comment]
Solved the issue in ccamp-optical-impairment I-D. In this document we will need to provide some overview text on why/how we use OTSi, maybe also include a reference. One requirement may be to co-route bidirectional connection the OTSI.

**Comment by aguoietf** [comment]
2023-12-14:
Check the latest text and model to make sure the above information is covered.

**Comment by aguoietf** [comment]
WDM tunnel is by default co-routed for forward /reverse directions
- check whether the base TE tunnel has this support for co-routed fwd/rev tunnel
