### ISSUE TITLE
Align the authors list with RFC7322 requirements

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang#44]
https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-media-channel-yang/blob/7c001e5f6502264c91c2eda77198840850e6e611/draft-ietf-ccamp-flexigrid-tunnel-yang-00.txt#L5-L20

**Comment by danielkinguk** [comment]
I did email all the authors a while ago, and suggested we split into Editors, Authors, Contributors. Not an enthusiastic response. We will have to organise front-page/author/contributors, based on recent contributions and effort.

**Comment by danielkinguk** [comment]
One vendor/University represented, and move other authors to backpage as contributors.

**Comment by aguoietf** [comment]
Updated author list already presented in the latest WDM tunnel document
