### ISSUE TITLE
Transceivers configuration

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang#53]
Few additional doubts:

Should we enforce all the transceivers within the same OTSiG to use the same fec-type?
Where is the transceiver configuration reported within the tunnel model
Is there a need to constraint which transceivers can be used by the OTSiG on the primary and/or on the secondary path?

See:  https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/issues/15#issuecomment-981861111

**Comment by aguoietf** [comment]
addressed by the latest rev-01
