### ISSUE TITLE
Look to merge WSON Tunnel and Flexi-Grid Tunnel I-D(s)

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang#56]
The plan is to merge both I-Ds, we need to investigate the effort required and what can be kept/removed. We will submit the new I-D shortly after IETF 117.

**Comment by aguoietf** [comment]
The proposal for the merge discussed on today's call - please review and comment.

[wdm-tunnel.txt](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-tunnel-yang/files/12749851/wdm-tunnel.txt)

**Comment by aguoietf** [comment]
Call Minutes 2023-10-05:

Agenda: discuss Aihua's YANG model proposal [here](https://github.com/aguoietf/draft-ietf-ccamp-wdm-tunnel-yang) to merge WSON and Flexi-grid tunnel.

Issues/Action Items:

> For transceiver constraints, operational-mode should be defined as a list instead of a single value
- Change has been introduced to the model
~~~~
    |  +--rw operational-modes*     string
~~~~

> It is suggested to add a new parameter, delta-power to the tunnel to indicate the per-channel power deviation at OMS section
- Added "delta-power" to the tunnel constraint
~~~~
  augment /te:te/te:tunnels/te:tunnel:
    +--rw wdm-constraint
....
       +--rw delta-power?                   l0-types:decimal-2-digits
~~~~

> It may be useful to know the maximum # of channels on a link to ensure the optical performance. Agreed that it is a system design / planning issue and does not associate to a particular tunnel, therefore no need to define it in the model
- No change to the YANG model is needed

> It was suggested to reuse the transmitter tuning range definitions in l0-types as opposed to re-defining the tx-tuning-range in the tunnel model
- Current l0-types-ext does not have a separate grouping definition for the tuning range. Also the existing tuning range definitions has all the parameters in read-only mode. Need to update l0-types grouping with the following changes:
  - define a new grouping, "transmitter-tuning-range" and remove the read-only statement.
  - add config=false to the container organizational-mode to make sure these parameters remain as read only in other YANG models such as ccamp-optical-impairment that use the same grouping
  - use this grouping as read-write mode in the wdm-tunnel model
~~~~
    +--rw wdm-constraint
       +--rw transceiver-constraint
       |  +--rw operational-modes*     string
       |  +--rw tx-tune-constraints
       |     +--rw min-central-frequency?    frequency-thz
       |     +--rw max-central-frequency?    frequency-thz
       |     +--rw transceiver-tunability?   frequency-ghz
~~~~

> Esther suggested to add two additional parameters, estimated GSNR at end of life, and estimated lowest (worst-case) GSNR for the computed path, in addition to the estimated current GSNR
- Added the two attributes to the YANG model
~~~~
  augment /te:te/te:tunnels/te:tunnel/te:primary-paths
            /te:primary-path/te:computed-paths-properties
            /te:computed-path-properties/te:path-properties:
    +--ro estimated-gsnr?          snr
    +--ro estimated-eol-gsnr?      snr
    +--ro estimated-lowest-gsnr?   snr
~~~~

**Comment by aguoietf** [comment]
Changed the type for delta-power to dB according to the call today (2023-10-19).
The change is [here](https://github.com/aguoietf/draft-ietf-ccamp-wdm-tunnel-yang/commit/afa68aedc8f8524f395a189e0d3abd6eb1c4d466#diff-ab333489b13f4a5d32ff19259bea1ee5c668f428b17d057c1d0b8e70858ff7af) 

OLD:
~~~~
       +--rw delta-power?                   l0-types:decimal-2-digits
~~~~

NEW:
~~~~
       +--rw delta-power?                  l0-types:gain-in-db-or-null
~~~~
