### ISSUE TITLE
Name for the channel spacing 

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang#57]
Need to change the definition of channel spacing in the context of flexible grid , in particular we need to deprecate
flexi-ch-spc-type and substitute with "flexi-ncf-granularity-type.
For more details see https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/56

**Comment by aguoietf** [comment]
closed. Issue was resolved in rfc9093-bis.
