### ISSUE TITLE
Contact non-CCAMP I-Ds that Reference WSON/Flexi-Grid Tunnel Models 

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-wdm-tunnel-yang#58]
ACTN POI and Path Computation I-Ds will be be updated to reference the WDM Tunnel I-D, but we will need to contact non-TEAS/CCAMP I-D authors to advise them on the update (general) Tunnel model and new I-D name.

**Comment by aguoietf** [comment]
the NMRG performance digital twin also references this draft. Changes needs to be made there.
